spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop